name: Setup Bun
description: Checkout, setup Bun, restore cache, install dependencies
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Restore bun cache
      uses: actions/cache@v5
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: ${{ runner.os }}-bun-

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
