/**
 * DTO (Data Transfer Object) and Command Model types for the API
 *
 * These types are derived from database models and represent the data structures
 * used in API requests and responses.
 */

import type { Tables } from "./db/database.types";

// ============================================================================
// Base Entity Types (derived from database)
// ============================================================================

/**
 * Base flashcard entity from database
 */
type FlashcardEntity = Tables<"flashcards">;

/**
 * Base generation entity from database
 */
type GenerationEntity = Tables<"generations">;

/**
 * Base generation error log entity from database
 */
type GenerationErrorLogEntity = Tables<"generation_error_logs">;

// ============================================================================
// Enums
// ============================================================================

/**
 * Flashcard status values
 */
export type FlashcardStatus = "new" | "learning" | "review" | "mastered";

/**
 * Flashcard source values
 */
export type FlashcardSource = "manual" | "ai" | "mixed";

/**
 * Sort order values
 */
export type SortOrder = "asc" | "desc";

/**
 * Flashcard sort field values
 */
export type FlashcardSortField = "created_at" | "updated_at" | "repetition_count";

/**
 * Generation sort field values
 */
export type GenerationSortField = "created_at" | "updated_at";

// ============================================================================
// Flashcard DTOs and Commands
// ============================================================================

/**
 * Flashcard DTO - represents a flashcard in API responses
 *
 * Derived directly from FlashcardEntity (database Row type).
 * Used in:
 * - GET /api/flashcards/:id (single flashcard response)
 * - GET /api/flashcards (paginated list response)
 * - POST /api/flashcards (created flashcard response)
 * - PATCH /api/flashcards/:id (updated flashcard response)
 *
 * Note: The source and status fields are typed as string in the database,
 * but are constrained by CHECK constraints to specific values (FlashcardSource and FlashcardStatus).
 * The API will always return valid enum values as defined by these constraints.
 */
export type FlashcardDTO = FlashcardEntity;

/**
 * Command to create a single flashcard
 *
 * Used in POST /api/flashcards request body.
 * Omits fields that are auto-generated by the database:
 * - id (auto-generated)
 * - user_id (set from authenticated user)
 * - created_at, updated_at (auto-managed by database)
 * - status (defaults to 'new')
 * - repetition_count (defaults to 0)
 *
 * The generation_id field is optional and should be provided when saving
 * AI-generated flashcard proposals that were previously created via POST /api/generations.
 * When provided, the backend will update generation statistics accordingly.
 */
export type CreateFlashcardCommand = Pick<FlashcardEntity, "front" | "back"> & {
  source?: FlashcardSource;
  generation_id?: number | null;
};

/**
 * Command to create one or more flashcards
 *
 * Used in POST /api/flashcards request body.
 * The API accepts either a single flashcard object or an array of flashcard objects.
 * When an array is provided, all flashcards are created in a single transaction.
 *
 * Response format:
 * - Single flashcard: returns FlashcardDTO
 * - Multiple flashcards: returns FlashcardDTO[]
 */
export type CreateFlashcardsCommand = CreateFlashcardCommand | CreateFlashcardCommand[];

/**
 * Command to update an existing flashcard
 *
 * Used in PATCH /api/flashcards/:id request body.
 * All fields are optional - only provided fields will be updated.
 *
 * Validation rules:
 * - front: max 200 characters (VARCHAR(200))
 * - back: max 500 characters (VARCHAR(500))
 * - status: must be one of: 'new', 'learning', 'review', 'mastered'
 * - source: must be one of: 'manual', 'ai', 'mixed'
 * - repetition_count: must be >= 0
 *
 * Note: Fields like id, user_id, created_at are not updatable via this command.
 * The updated_at field is automatically managed by the database.
 */
export type UpdateFlashcardCommand = Partial<Pick<FlashcardEntity, "front" | "back" | "repetition_count">> & {
  status?: FlashcardStatus;
  source?: FlashcardSource;
};

/**
 * Response for successful flashcard deletion
 *
 * Used in DELETE /api/flashcards/:id response body.
 * Returns confirmation message and the ID of the deleted flashcard.
 */
export interface DeleteFlashcardResponse {
  message: string;
  id: number;
}

// ============================================================================
// Generation DTOs and Commands
// ============================================================================

/**
 * Generation DTO - represents a generation session in API responses
 *
 * Derived directly from GenerationEntity (database Row type).
 * Used in:
 * - GET /api/generations/:id (single generation response)
 * - GET /api/generations (paginated list response)
 *
 * Contains statistics about AI generation sessions, including:
 * - generated_count: total number of flashcard proposals generated
 * - accepted_unedited_count: proposals accepted without editing
 * - accepted_edited_count: proposals accepted after user editing
 */
export type GenerationDTO = GenerationEntity;

/**
 * Command to create a new AI generation session
 *
 * Used in POST /api/generations request body.
 *
 * Validation rules:
 * - source_text: required, string, min 1000 characters, max 10000 characters
 *
 * This command triggers AI generation of flashcard proposals from the provided source text.
 * The generated flashcards are returned as proposals (not yet saved to database) and require
 * user approval before being saved via POST /api/flashcards.
 * The AI model is selected automatically by the backend.
 */
export interface CreateGenerationCommand {
  source_text: string;
}

/**
 * Flashcard proposal (not yet saved to database)
 *
 * Represents an AI-generated flashcard suggestion returned by POST /api/generations.
 * These are proposals that require user review and approval before being saved.
 *
 * The user can:
 * - Accept the proposal as-is (source will be 'ai')
 * - Edit the proposal before accepting (source will be 'mixed')
 * - Reject the proposal (not saved)
 *
 * To save accepted proposals, use POST /api/flashcards with the selected proposals.
 */
export interface FlashcardProposal {
  front: string;
  back: string;
  /**
   * Indicates this proposal was generated by AI.
   * For proposals returned from POST /api/generations, source is always 'ai'.
   */
  source: "ai";
}

/**
 * Metadata about a generation session
 *
 * Included in GenerationProposalsResponse to provide statistics about the AI generation process.
 * - generated_count: number of flashcard proposals generated
 * - source_text_length: length of the source text in characters
 * - generation_duration_ms: time taken for AI generation in milliseconds
 */
export interface GenerationMetadata {
  generated_count: number;
  source_text_length: number;
  generation_duration_ms: number;
}

/**
 * Response from POST /api/generations
 *
 * Contains the generation session ID, AI-generated flashcard proposals, and generation metadata.
 *
 * Important: The flashcardsProposals are NOT yet saved to the database. They are suggestions
 * that require user approval. To save accepted proposals, the user must call POST /api/flashcards
 * with the selected flashcard proposals.
 *
 * The generation_id can be used to link saved flashcards back to this generation session
 * when creating them via POST /api/flashcards with generation_id included.
 */
export interface GenerationProposalsResponse {
  generation_id: number;
  flashcardsProposals: FlashcardProposal[];
  metadata: GenerationMetadata;
}

// ============================================================================
// Generation Error Log DTOs
// ============================================================================

/**
 * Generation Error Log DTO - represents an error log entry in API responses
 *
 * Derived from GenerationErrorLogEntity (database Row type) with an additional raw_error field.
 *
 * Used in GET /api/generation-error-logs responses.
 *
 * The raw_error field contains the raw error object/message from the AI API call,
 * serialized as a JSON string. This field is not stored in the database but is
 * included in API responses for debugging purposes.
 */
export type GenerationErrorLogDTO = GenerationErrorLogEntity & {
  raw_error?: string;
};

// ============================================================================
// Query Parameters
// ============================================================================

/**
 * Query parameters for GET /api/flashcards
 */
export interface FlashcardQueryParams {
  page?: number;
  limit?: number;
  status?: FlashcardStatus;
  source?: FlashcardSource;
  sort?: FlashcardSortField;
  order?: SortOrder;
}

/**
 * Query parameters for GET /api/generations
 */
export interface GenerationQueryParams {
  page?: number;
  limit?: number;
  sort?: GenerationSortField;
  order?: SortOrder;
}

/**
 * Query parameters for GET /api/generation-error-logs
 */
export interface GenerationErrorLogQueryParams {
  page?: number;
  limit?: number;
}

// ============================================================================
// Pagination
// ============================================================================

/**
 * Pagination metadata included in paginated responses
 */
export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  total_pages: number;
}

/**
 * Paginated response wrapper
 */
export interface PaginatedResponse<T> {
  data: T[];
  pagination: PaginationMeta;
}

// ============================================================================
// Paginated Response Types
// ============================================================================

/**
 * Paginated response for GET /api/flashcards
 */
export type PaginatedFlashcardsResponse = PaginatedResponse<FlashcardDTO>;

/**
 * Paginated response for GET /api/generations
 */
export type PaginatedGenerationsResponse = PaginatedResponse<GenerationDTO>;

/**
 * Paginated response for GET /api/generation-error-logs
 */
export type PaginatedGenerationErrorLogsResponse = PaginatedResponse<GenerationErrorLogDTO>;

// ============================================================================
// Error Response
// ============================================================================

/**
 * Standard error response format
 */
export interface ErrorResponse {
  error: {
    code: string;
    message: string;
    details?: Record<string, unknown>;
  };
}

/**
 * Common error codes used in ErrorResponse
 */
export type ErrorCode =
  | "VALIDATION_ERROR"
  | "UNAUTHORIZED"
  | "NOT_FOUND"
  | "RATE_LIMIT_EXCEEDED"
  | "AI_API_ERROR"
  | "DATABASE_ERROR"
  | "INTERNAL_SERVER_ERROR";
